syntax = "proto3";

package velony.identity.api.v1;

import "velony/identity/api/v1/user.proto";
import "velony/identity/api/v1/auth.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/velonyapp/identity/gen/api/v1;apiv1";

service IdentityService {
  option (google.api.default_host) = "identity.velony.app";

  rpc GetUser(GetUserRequest) returns (User) {
    option (google.api.http) = {
      get: "/v1/{name=users/*}"
    };
    option (google.api.method_signature) = "name";
  }

  rpc BatchGetUsers(BatchGetUsersRequest) returns (BatchGetUsersResponse) {
    option (google.api.http) = {
      get: "/v1/users:batchGet"
    };
  }

  rpc UpdateUser(UpdateUserRequest) returns (User) {
    option (google.api.http) = {
      patch: "/v1/{user.name=users/*}"
      body : "user"
    };
    option (google.api.method_signature) = "user,update_mask";
  }

  rpc RequestUserEmailChange(RequestUserEmailChangeRequest) returns (RequestUserEmailChangeResponse) {
    option (google.api.http) = {
      post: "/v1/{name=users/*}:requestEmailChange"
      body: "*"
    };
  }

  rpc ConfirmUserEmailChange(ConfirmUserEmailChangeRequest) returns (ConfirmUserEmailChangeResponse) {
    option (google.api.http) = {
      post: "/v1/{name=users/*}:confirmEmailChange"
      body: "*"
    };
  }

  rpc RequestUserAvatarChange(RequestUserAvatarChangeRequest) returns (RequestUserAvatarChangeResponse) {
    option (google.api.http) = {
      post: "/v1/{name=users/*}:requestAvatarChange"
      body: "*"
    };
  }

  rpc DeleteUser(DeleteUserRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      delete: "/v1/{name=users/*}"
    };
    option (google.api.method_signature) = "name";
  }

  rpc LoginAuth(LoginAuthRequest) returns (LoginAuthResponse) {
    option (google.api.http) = {
      post: "/v1/auth:login"
      body: "*"
    };
    option (google.api.method_signature) = "identity,password";
  }

  rpc RegisterAuth(RegisterAuthRequest) returns (RegisterAuthResponse) {
    option (google.api.http) = {
      post: "/v1/auth:register"
      body: "*"
    };
    option (google.api.method_signature) = "full_name,username,password";
  }

  rpc RefreshAuth(RefreshAuthRequest) returns (RefreshAuthResponse) {
    option (google.api.http) = {
      post: "/v1/auth:refresh"
      body: "*"
    };
    option (google.api.method_signature) = "refresh_token";
  }
}