syntax = "proto3";

package velony.identity.api.v1;

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/velonyapp/identity/gen/api/v1;apiv1";

message User {
  option (google.api.resource) = {
    type    : "identity.velony.app/User"
    pattern : "users/{user}"
    singular: "user"
    plural  : "users"
  };

  string name = 1 [(google.api.field_behavior) = IDENTIFIER];

  string          username   = 2 [(google.api.field_behavior) = REQUIRED];
  optional string email      = 3 [(google.api.field_behavior) = OUTPUT_ONLY];
  string          full_name  = 4 [(google.api.field_behavior) = REQUIRED];
  optional string avatar_key = 5 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message GetUserRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "identity.velony.app/User"
    }
  ];
}

message BatchGetUsersRequest {
  // max batch = 100
  repeated string names = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "identity.velony.app/User"
    }
  ];
}

message BatchGetUsersResponse {
  repeated User users = 1;
}

message UpdateUserRequest {
  User user = 1 [(google.api.field_behavior) = REQUIRED];

  google.protobuf.FieldMask update_mask = 2[(google.api.field_behavior) = OPTIONAL];
}

message RequestUserEmailChangeRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "identity.velony.app/User"
    }
  ];

  string email = 2 [(google.api.field_behavior) = REQUIRED];
}

message RequestUserEmailChangeResponse {}

message ConfirmUserEmailChangeRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "identity.velony.app/User"
    }
  ];

  string token = 2 [(google.api.field_behavior) = REQUIRED];
}

message ConfirmUserEmailChangeResponse {}

message RequestUserAvatarChangeRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "identity.velony.app/User"
    }
  ];
}

message RequestUserAvatarChangeResponse {
  string upload_url = 1;
}

message DeleteUserRequest {
  string name = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
    type: "user.velony.app/User"
    }
  ];
}
