// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Observability_Protocol int32

const (
	Observability_PROTOCOL_UNSPECIFIED   Observability_Protocol = 0
	Observability_PROTOCOL_GRPC          Observability_Protocol = 1
	Observability_PROTOCOL_HTTP_PROTOBUF Observability_Protocol = 2
)

// Enum value maps for Observability_Protocol.
var (
	Observability_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_GRPC",
		2: "PROTOCOL_HTTP_PROTOBUF",
	}
	Observability_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":   0,
		"PROTOCOL_GRPC":          1,
		"PROTOCOL_HTTP_PROTOBUF": 2,
	}
)

func (x Observability_Protocol) Enum() *Observability_Protocol {
	p := new(Observability_Protocol)
	*p = x
	return p
}

func (x Observability_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Observability_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Observability_Protocol) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Observability_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Observability_Protocol.Descriptor instead.
func (Observability_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     *Transport             `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Observability *Observability         `protobuf:"bytes,4,opt,name=observability,proto3" json:"observability,omitempty"`
	Gateway       *Gateway               `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Bootstrap) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

type Transport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Transport_HTTP        `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Transport_GRPC        `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Transport) GetHttp() *Transport_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Transport) GetGrpc() *Transport_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mysql         *Data_MySQL            `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetMysql() *Data_MySQL {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *Auth_AccessToken      `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  *Auth_RefreshToken     `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetAccessToken() *Auth_AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *Auth) GetRefreshToken() *Auth_RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type Observability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracing       *Observability_Tracing `protobuf:"bytes,1,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Metrics       *Observability_Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Observability) GetTracing() *Observability_Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Observability) GetMetrics() *Observability_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Gateway_Asset         `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Gateway) GetAsset() *Gateway_Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type Transport_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_HTTP) Reset() {
	*x = Transport_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_HTTP) ProtoMessage() {}

func (x *Transport_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_HTTP.ProtoReflect.Descriptor instead.
func (*Transport_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Transport_HTTP) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Transport_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_GRPC) Reset() {
	*x = Transport_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_GRPC) ProtoMessage() {}

func (x *Transport_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_GRPC.ProtoReflect.Descriptor instead.
func (*Transport_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Transport_GRPC) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_MySQL struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dsn                   string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxOpenConnections    *uint32                `protobuf:"varint,2,opt,name=max_open_connections,json=maxOpenConnections,proto3,oneof" json:"max_open_connections,omitempty"`
	MaxIdleConnections    *uint32                `protobuf:"varint,3,opt,name=max_idle_connections,json=maxIdleConnections,proto3,oneof" json:"max_idle_connections,omitempty"`
	MaxConnectionLifetime *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_connection_lifetime,json=maxConnectionLifetime,proto3" json:"max_connection_lifetime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Data_MySQL) Reset() {
	*x = Data_MySQL{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MySQL) ProtoMessage() {}

func (x *Data_MySQL) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MySQL.ProtoReflect.Descriptor instead.
func (*Data_MySQL) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_MySQL) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_MySQL) GetMaxOpenConnections() uint32 {
	if x != nil && x.MaxOpenConnections != nil {
		return *x.MaxOpenConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxIdleConnections() uint32 {
	if x != nil && x.MaxIdleConnections != nil {
		return *x.MaxIdleConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxConnectionLifetime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnectionLifetime
	}
	return nil
}

type Data_Redis struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Dsn                  string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxActiveConnections *uint32                `protobuf:"varint,2,opt,name=max_active_connections,json=maxActiveConnections,proto3,oneof" json:"max_active_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_Redis) GetMaxActiveConnections() uint32 {
	if x != nil && x.MaxActiveConnections != nil {
		return *x.MaxActiveConnections
	}
	return 0
}

type Auth_AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_AccessToken) Reset() {
	*x = Auth_AccessToken{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_AccessToken) ProtoMessage() {}

func (x *Auth_AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_AccessToken.ProtoReflect.Descriptor instead.
func (*Auth_AccessToken) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Auth_AccessToken) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Auth_AccessToken) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Auth_RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth_RefreshToken) Reset() {
	*x = Auth_RefreshToken{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth_RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_RefreshToken) ProtoMessage() {}

func (x *Auth_RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_RefreshToken.ProtoReflect.Descriptor instead.
func (*Auth_RefreshToken) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Auth_RefreshToken) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Observability_Tracing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Observability_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=kratos.api.Observability_Protocol" json:"protocol,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Authorization *string                `protobuf:"bytes,3,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	SampleRatio   *float64               `protobuf:"fixed64,4,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Tracing) Reset() {
	*x = Observability_Tracing{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Tracing) ProtoMessage() {}

func (x *Observability_Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Tracing.ProtoReflect.Descriptor instead.
func (*Observability_Tracing) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Observability_Tracing) GetProtocol() Observability_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Observability_PROTOCOL_UNSPECIFIED
}

func (x *Observability_Tracing) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Tracing) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *Observability_Tracing) GetSampleRatio() float64 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

type Observability_Metrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       Observability_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=kratos.api.Observability_Protocol" json:"protocol,omitempty"`
	Endpoint       string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Authorization  *string                `protobuf:"bytes,3,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	ExportInterval *durationpb.Duration   `protobuf:"bytes,4,opt,name=export_interval,json=exportInterval,proto3" json:"export_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Observability_Metrics) Reset() {
	*x = Observability_Metrics{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Metrics) ProtoMessage() {}

func (x *Observability_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Metrics.ProtoReflect.Descriptor instead.
func (*Observability_Metrics) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Observability_Metrics) GetProtocol() Observability_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Observability_PROTOCOL_UNSPECIFIED
}

func (x *Observability_Metrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Metrics) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *Observability_Metrics) GetExportInterval() *durationpb.Duration {
	if x != nil {
		return x.ExportInterval
	}
	return nil
}

type Gateway_Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway_Asset) Reset() {
	*x = Gateway_Asset{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway_Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway_Asset) ProtoMessage() {}

func (x *Gateway_Asset) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway_Asset.ProtoReflect.Descriptor instead.
func (*Gateway_Asset) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Gateway_Asset) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Gateway_Asset) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"\x9c\x02\n" +
	"\tBootstrap\x12;\n" +
	"\ttransport\x18\x01 \x01(\v2\x15.kratos.api.TransportB\x06\xbaH\x03\xc8\x01\x01R\ttransport\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataB\x06\xbaH\x03\xc8\x01\x01R\x04data\x12,\n" +
	"\x04auth\x18\x03 \x01(\v2\x10.kratos.api.AuthB\x06\xbaH\x03\xc8\x01\x01R\x04auth\x12?\n" +
	"\robservability\x18\x04 \x01(\v2\x19.kratos.api.ObservabilityR\robservability\x125\n" +
	"\agateway\x18\x05 \x01(\v2\x13.kratos.api.GatewayB\x06\xbaH\x03\xc8\x01\x01R\agateway\"\xd1\x02\n" +
	"\tTransport\x126\n" +
	"\x04http\x18\x01 \x01(\v2\x1a.kratos.api.Transport.HTTPB\x06\xbaH\x03\xc8\x01\x01R\x04http\x126\n" +
	"\x04grpc\x18\x02 \x01(\v2\x1a.kratos.api.Transport.GRPCB\x06\xbaH\x03\xc8\x01\x01R\x04grpc\x1ai\n" +
	"\x04HTTP\x12\"\n" +
	"\aaddress\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\aaddress\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\x1ai\n" +
	"\x04GRPC\x12\"\n" +
	"\aaddress\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\aaddress\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\"\xd8\x05\n" +
	"\x04Data\x124\n" +
	"\x05mysql\x18\x01 \x01(\v2\x16.kratos.api.Data.MySQLB\x06\xbaH\x03\xc8\x01\x01R\x05mysql\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\xf1\x03\n" +
	"\x05MySQL\x12\x19\n" +
	"\x03dsn\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03dsn\x125\n" +
	"\x14max_open_connections\x18\x02 \x01(\rH\x00R\x12maxOpenConnections\x88\x01\x01\x125\n" +
	"\x14max_idle_connections\x18\x03 \x01(\rH\x01R\x12maxIdleConnections\x88\x01\x01\x12[\n" +
	"\x17max_connection_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x022\x00R\x15maxConnectionLifetime:\xcf\x01\xbaH\xcb\x01\x1a\xc8\x01\n" +
	"\x11mysql.pool_limits\x12Xmax_idle_connections cannot exceed max_open_connections unless max_open_connections is 0\x1aYthis.max_open_connections == 0u || this.max_idle_connections <= this.max_open_connectionsB\x17\n" +
	"\x15_max_open_connectionsB\x17\n" +
	"\x15_max_idle_connections\x1ax\n" +
	"\x05Redis\x12\x19\n" +
	"\x03dsn\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03dsn\x129\n" +
	"\x16max_active_connections\x18\x02 \x01(\rH\x00R\x14maxActiveConnections\x88\x01\x01B\x19\n" +
	"\x17_max_active_connections\"\xcf\x02\n" +
	"\x04Auth\x12G\n" +
	"\faccess_token\x18\x01 \x01(\v2\x1c.kratos.api.Auth.AccessTokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12J\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\x1d.kratos.api.Auth.RefreshTokenB\x06\xbaH\x03\xc8\x01\x01R\frefreshToken\x1ah\n" +
	"\vAccessToken\x12\x1f\n" +
	"\x06secret\x18\x01 \x01(\tB\a\xbaH\x04r\x02  R\x06secret\x128\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x03ttl\x1aH\n" +
	"\fRefreshToken\x128\n" +
	"\x03ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x03ttl\"\x87\x06\n" +
	"\rObservability\x12;\n" +
	"\atracing\x18\x01 \x01(\v2!.kratos.api.Observability.TracingR\atracing\x12;\n" +
	"\ametrics\x18\x02 \x01(\v2!.kratos.api.Observability.MetricsR\ametrics\x1a\x92\x02\n" +
	"\aTracing\x12J\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\".kratos.api.Observability.ProtocolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bprotocol\x12#\n" +
	"\bendpoint\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x122\n" +
	"\rauthorization\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\rauthorization\x88\x01\x01\x12?\n" +
	"\fsample_ratio\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\vsampleRatio\x88\x01\x01B\x10\n" +
	"\x0e_authorizationB\x0f\n" +
	"\r_sample_ratio\x1a\x91\x02\n" +
	"\aMetrics\x12J\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\".kratos.api.Observability.ProtocolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bprotocol\x12#\n" +
	"\bendpoint\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x122\n" +
	"\rauthorization\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\rauthorization\x88\x01\x01\x12O\n" +
	"\x0fexport_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x0eexportIntervalB\x10\n" +
	"\x0e_authorization\"S\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPROTOCOL_GRPC\x10\x01\x12\x1a\n" +
	"\x16PROTOCOL_HTTP_PROTOBUF\x10\x02\"\xb2\x01\n" +
	"\aGateway\x127\n" +
	"\x05asset\x18\x01 \x01(\v2\x19.kratos.api.Gateway.AssetB\x06\xbaH\x03\xc8\x01\x01R\x05asset\x1an\n" +
	"\x05Asset\x12#\n" +
	"\bendpoint\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x12@\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\atimeoutB-Z+github.com/velonyapp/identity/internal/confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_conf_conf_proto_goTypes = []any{
	(Observability_Protocol)(0),   // 0: kratos.api.Observability.Protocol
	(*Bootstrap)(nil),             // 1: kratos.api.Bootstrap
	(*Transport)(nil),             // 2: kratos.api.Transport
	(*Data)(nil),                  // 3: kratos.api.Data
	(*Auth)(nil),                  // 4: kratos.api.Auth
	(*Observability)(nil),         // 5: kratos.api.Observability
	(*Gateway)(nil),               // 6: kratos.api.Gateway
	(*Transport_HTTP)(nil),        // 7: kratos.api.Transport.HTTP
	(*Transport_GRPC)(nil),        // 8: kratos.api.Transport.GRPC
	(*Data_MySQL)(nil),            // 9: kratos.api.Data.MySQL
	(*Data_Redis)(nil),            // 10: kratos.api.Data.Redis
	(*Auth_AccessToken)(nil),      // 11: kratos.api.Auth.AccessToken
	(*Auth_RefreshToken)(nil),     // 12: kratos.api.Auth.RefreshToken
	(*Observability_Tracing)(nil), // 13: kratos.api.Observability.Tracing
	(*Observability_Metrics)(nil), // 14: kratos.api.Observability.Metrics
	(*Gateway_Asset)(nil),         // 15: kratos.api.Gateway.Asset
	(*durationpb.Duration)(nil),   // 16: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	2,  // 0: kratos.api.Bootstrap.transport:type_name -> kratos.api.Transport
	3,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	4,  // 2: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	5,  // 3: kratos.api.Bootstrap.observability:type_name -> kratos.api.Observability
	6,  // 4: kratos.api.Bootstrap.gateway:type_name -> kratos.api.Gateway
	7,  // 5: kratos.api.Transport.http:type_name -> kratos.api.Transport.HTTP
	8,  // 6: kratos.api.Transport.grpc:type_name -> kratos.api.Transport.GRPC
	9,  // 7: kratos.api.Data.mysql:type_name -> kratos.api.Data.MySQL
	10, // 8: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	11, // 9: kratos.api.Auth.access_token:type_name -> kratos.api.Auth.AccessToken
	12, // 10: kratos.api.Auth.refresh_token:type_name -> kratos.api.Auth.RefreshToken
	13, // 11: kratos.api.Observability.tracing:type_name -> kratos.api.Observability.Tracing
	14, // 12: kratos.api.Observability.metrics:type_name -> kratos.api.Observability.Metrics
	15, // 13: kratos.api.Gateway.asset:type_name -> kratos.api.Gateway.Asset
	16, // 14: kratos.api.Transport.HTTP.timeout:type_name -> google.protobuf.Duration
	16, // 15: kratos.api.Transport.GRPC.timeout:type_name -> google.protobuf.Duration
	16, // 16: kratos.api.Data.MySQL.max_connection_lifetime:type_name -> google.protobuf.Duration
	16, // 17: kratos.api.Auth.AccessToken.ttl:type_name -> google.protobuf.Duration
	16, // 18: kratos.api.Auth.RefreshToken.ttl:type_name -> google.protobuf.Duration
	0,  // 19: kratos.api.Observability.Tracing.protocol:type_name -> kratos.api.Observability.Protocol
	0,  // 20: kratos.api.Observability.Metrics.protocol:type_name -> kratos.api.Observability.Protocol
	16, // 21: kratos.api.Observability.Metrics.export_interval:type_name -> google.protobuf.Duration
	16, // 22: kratos.api.Gateway.Asset.timeout:type_name -> google.protobuf.Duration
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	file_conf_conf_proto_msgTypes[8].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[9].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[12].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
