// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Observability_Protocol int32

const (
	Observability_PROTOCOL_UNSPECIFIED   Observability_Protocol = 0
	Observability_PROTOCOL_GRPC          Observability_Protocol = 1
	Observability_PROTOCOL_HTTP_PROTOBUF Observability_Protocol = 2
)

// Enum value maps for Observability_Protocol.
var (
	Observability_Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_GRPC",
		2: "PROTOCOL_HTTP_PROTOBUF",
	}
	Observability_Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":   0,
		"PROTOCOL_GRPC":          1,
		"PROTOCOL_HTTP_PROTOBUF": 2,
	}
)

func (x Observability_Protocol) Enum() *Observability_Protocol {
	p := new(Observability_Protocol)
	*p = x
	return p
}

func (x Observability_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Observability_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Observability_Protocol) Type() protoreflect.EnumType {
	return &file_conf_conf_proto_enumTypes[0]
}

func (x Observability_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Observability_Protocol.Descriptor instead.
func (Observability_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     *Transport             `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Security      *Security              `protobuf:"bytes,3,opt,name=security,proto3" json:"security,omitempty"`
	Observability *Observability         `protobuf:"bytes,4,opt,name=observability,proto3" json:"observability,omitempty"`
	Gateway       *Gateway               `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Bootstrap) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

type Transport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Transport_HTTP        `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Transport_GRPC        `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Kafka         *Transport_Kafka       `protobuf:"bytes,3,opt,name=kafka,proto3" json:"kafka,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Transport) GetHttp() *Transport_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Transport) GetGrpc() *Transport_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Transport) GetKafka() *Transport_Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mysql         *Data_MySQL            `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetMysql() *Data_MySQL {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Security struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	AccessToken         *Security_AccessToken         `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken        *Security_RefreshToken        `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	EmailChangeRequest  *Security_EmailChangeRequest  `protobuf:"bytes,3,opt,name=email_change_request,json=emailChangeRequest,proto3" json:"email_change_request,omitempty"`
	AvatarChangeRequest *Security_AvatarChangeRequest `protobuf:"bytes,4,opt,name=avatar_change_request,json=avatarChangeRequest,proto3" json:"avatar_change_request,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Security) GetAccessToken() *Security_AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *Security) GetRefreshToken() *Security_RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *Security) GetEmailChangeRequest() *Security_EmailChangeRequest {
	if x != nil {
		return x.EmailChangeRequest
	}
	return nil
}

func (x *Security) GetAvatarChangeRequest() *Security_AvatarChangeRequest {
	if x != nil {
		return x.AvatarChangeRequest
	}
	return nil
}

type Observability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracing       *Observability_Tracing `protobuf:"bytes,1,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Metrics       *Observability_Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Observability) GetTracing() *Observability_Tracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

func (x *Observability) GetMetrics() *Observability_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Gateway_Asset         `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Gateway) GetAsset() *Gateway_Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type Transport_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_HTTP) Reset() {
	*x = Transport_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_HTTP) ProtoMessage() {}

func (x *Transport_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_HTTP.ProtoReflect.Descriptor instead.
func (*Transport_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Transport_HTTP) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Transport_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_GRPC) Reset() {
	*x = Transport_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_GRPC) ProtoMessage() {}

func (x *Transport_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_GRPC.ProtoReflect.Descriptor instead.
func (*Transport_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Transport_GRPC) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Transport_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Transport_Kafka struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Brokers       []string                   `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Timeout       *durationpb.Duration       `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Consumers     *Transport_Kafka_Consumers `protobuf:"bytes,3,opt,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_Kafka) Reset() {
	*x = Transport_Kafka{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_Kafka) ProtoMessage() {}

func (x *Transport_Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_Kafka.ProtoReflect.Descriptor instead.
func (*Transport_Kafka) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Transport_Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Transport_Kafka) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Transport_Kafka) GetConsumers() *Transport_Kafka_Consumers {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type Transport_Kafka_Consumers struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	AssetImage    *Transport_Kafka_Consumers_AssetImage `protobuf:"bytes,1,opt,name=asset_image,json=assetImage,proto3" json:"asset_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_Kafka_Consumers) Reset() {
	*x = Transport_Kafka_Consumers{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_Kafka_Consumers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_Kafka_Consumers) ProtoMessage() {}

func (x *Transport_Kafka_Consumers) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_Kafka_Consumers.ProtoReflect.Descriptor instead.
func (*Transport_Kafka_Consumers) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *Transport_Kafka_Consumers) GetAssetImage() *Transport_Kafka_Consumers_AssetImage {
	if x != nil {
		return x.AssetImage
	}
	return nil
}

type Transport_Kafka_Consumers_AssetImage struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Topic         string                                       `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId       string                                       `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Events        *Transport_Kafka_Consumers_AssetImage_Events `protobuf:"bytes,3,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport_Kafka_Consumers_AssetImage) Reset() {
	*x = Transport_Kafka_Consumers_AssetImage{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_Kafka_Consumers_AssetImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_Kafka_Consumers_AssetImage) ProtoMessage() {}

func (x *Transport_Kafka_Consumers_AssetImage) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_Kafka_Consumers_AssetImage.ProtoReflect.Descriptor instead.
func (*Transport_Kafka_Consumers_AssetImage) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2, 0, 0}
}

func (x *Transport_Kafka_Consumers_AssetImage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Transport_Kafka_Consumers_AssetImage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Transport_Kafka_Consumers_AssetImage) GetEvents() *Transport_Kafka_Consumers_AssetImage_Events {
	if x != nil {
		return x.Events
	}
	return nil
}

type Transport_Kafka_Consumers_AssetImage_Events struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Created                string                 `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	ObjectExistenceUpdated string                 `protobuf:"bytes,2,opt,name=object_existence_updated,json=objectExistenceUpdated,proto3" json:"object_existence_updated,omitempty"`
	Deleted                string                 `protobuf:"bytes,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Transport_Kafka_Consumers_AssetImage_Events) Reset() {
	*x = Transport_Kafka_Consumers_AssetImage_Events{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport_Kafka_Consumers_AssetImage_Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport_Kafka_Consumers_AssetImage_Events) ProtoMessage() {}

func (x *Transport_Kafka_Consumers_AssetImage_Events) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport_Kafka_Consumers_AssetImage_Events.ProtoReflect.Descriptor instead.
func (*Transport_Kafka_Consumers_AssetImage_Events) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 2, 0, 0, 0}
}

func (x *Transport_Kafka_Consumers_AssetImage_Events) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Transport_Kafka_Consumers_AssetImage_Events) GetObjectExistenceUpdated() string {
	if x != nil {
		return x.ObjectExistenceUpdated
	}
	return ""
}

func (x *Transport_Kafka_Consumers_AssetImage_Events) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type Data_MySQL struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dsn                   string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxOpenConnections    *uint32                `protobuf:"varint,2,opt,name=max_open_connections,json=maxOpenConnections,proto3,oneof" json:"max_open_connections,omitempty"`
	MaxIdleConnections    *uint32                `protobuf:"varint,3,opt,name=max_idle_connections,json=maxIdleConnections,proto3,oneof" json:"max_idle_connections,omitempty"`
	MaxConnectionLifetime *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_connection_lifetime,json=maxConnectionLifetime,proto3" json:"max_connection_lifetime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Data_MySQL) Reset() {
	*x = Data_MySQL{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MySQL) ProtoMessage() {}

func (x *Data_MySQL) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MySQL.ProtoReflect.Descriptor instead.
func (*Data_MySQL) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_MySQL) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_MySQL) GetMaxOpenConnections() uint32 {
	if x != nil && x.MaxOpenConnections != nil {
		return *x.MaxOpenConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxIdleConnections() uint32 {
	if x != nil && x.MaxIdleConnections != nil {
		return *x.MaxIdleConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxConnectionLifetime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnectionLifetime
	}
	return nil
}

type Data_Redis struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Dsn                  string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxActiveConnections *uint32                `protobuf:"varint,2,opt,name=max_active_connections,json=maxActiveConnections,proto3,oneof" json:"max_active_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_Redis) GetMaxActiveConnections() uint32 {
	if x != nil && x.MaxActiveConnections != nil {
		return *x.MaxActiveConnections
	}
	return 0
}

type Security_AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_AccessToken) Reset() {
	*x = Security_AccessToken{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_AccessToken) ProtoMessage() {}

func (x *Security_AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_AccessToken.ProtoReflect.Descriptor instead.
func (*Security_AccessToken) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Security_AccessToken) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Security_AccessToken) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Security_RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_RefreshToken) Reset() {
	*x = Security_RefreshToken{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_RefreshToken) ProtoMessage() {}

func (x *Security_RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_RefreshToken.ProtoReflect.Descriptor instead.
func (*Security_RefreshToken) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Security_RefreshToken) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Security_EmailChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_EmailChangeRequest) Reset() {
	*x = Security_EmailChangeRequest{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_EmailChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_EmailChangeRequest) ProtoMessage() {}

func (x *Security_EmailChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_EmailChangeRequest.ProtoReflect.Descriptor instead.
func (*Security_EmailChangeRequest) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Security_EmailChangeRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Security_EmailChangeRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Security_AvatarChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_AvatarChangeRequest) Reset() {
	*x = Security_AvatarChangeRequest{}
	mi := &file_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_AvatarChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_AvatarChangeRequest) ProtoMessage() {}

func (x *Security_AvatarChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_AvatarChangeRequest.ProtoReflect.Descriptor instead.
func (*Security_AvatarChangeRequest) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 3}
}

func (x *Security_AvatarChangeRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type Observability_Tracing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Observability_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=kratos.api.Observability_Protocol" json:"protocol,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Authorization *string                `protobuf:"bytes,3,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	SampleRatio   *float64               `protobuf:"fixed64,4,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Tracing) Reset() {
	*x = Observability_Tracing{}
	mi := &file_conf_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Tracing) ProtoMessage() {}

func (x *Observability_Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Tracing.ProtoReflect.Descriptor instead.
func (*Observability_Tracing) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Observability_Tracing) GetProtocol() Observability_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Observability_PROTOCOL_UNSPECIFIED
}

func (x *Observability_Tracing) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Tracing) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *Observability_Tracing) GetSampleRatio() float64 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

type Observability_Metrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       Observability_Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=kratos.api.Observability_Protocol" json:"protocol,omitempty"`
	Endpoint       string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Authorization  *string                `protobuf:"bytes,3,opt,name=authorization,proto3,oneof" json:"authorization,omitempty"`
	ExportInterval *durationpb.Duration   `protobuf:"bytes,4,opt,name=export_interval,json=exportInterval,proto3" json:"export_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Observability_Metrics) Reset() {
	*x = Observability_Metrics{}
	mi := &file_conf_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Metrics) ProtoMessage() {}

func (x *Observability_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Metrics.ProtoReflect.Descriptor instead.
func (*Observability_Metrics) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Observability_Metrics) GetProtocol() Observability_Protocol {
	if x != nil {
		return x.Protocol
	}
	return Observability_PROTOCOL_UNSPECIFIED
}

func (x *Observability_Metrics) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Metrics) GetAuthorization() string {
	if x != nil && x.Authorization != nil {
		return *x.Authorization
	}
	return ""
}

func (x *Observability_Metrics) GetExportInterval() *durationpb.Duration {
	if x != nil {
		return x.ExportInterval
	}
	return nil
}

type Gateway_Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway_Asset) Reset() {
	*x = Gateway_Asset{}
	mi := &file_conf_conf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway_Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway_Asset) ProtoMessage() {}

func (x *Gateway_Asset) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway_Asset.ProtoReflect.Descriptor instead.
func (*Gateway_Asset) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Gateway_Asset) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Gateway_Asset) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa8\x02\n" +
	"\tBootstrap\x12;\n" +
	"\ttransport\x18\x01 \x01(\v2\x15.kratos.api.TransportB\x06\xbaH\x03\xc8\x01\x01R\ttransport\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataB\x06\xbaH\x03\xc8\x01\x01R\x04data\x128\n" +
	"\bsecurity\x18\x03 \x01(\v2\x14.kratos.api.SecurityB\x06\xbaH\x03\xc8\x01\x01R\bsecurity\x12?\n" +
	"\robservability\x18\x04 \x01(\v2\x19.kratos.api.ObservabilityR\robservability\x125\n" +
	"\agateway\x18\x05 \x01(\v2\x13.kratos.api.GatewayB\x06\xbaH\x03\xc8\x01\x01R\agateway\"\xf6\a\n" +
	"\tTransport\x126\n" +
	"\x04http\x18\x01 \x01(\v2\x1a.kratos.api.Transport.HTTPB\x06\xbaH\x03\xc8\x01\x01R\x04http\x126\n" +
	"\x04grpc\x18\x02 \x01(\v2\x1a.kratos.api.Transport.GRPCB\x06\xbaH\x03\xc8\x01\x01R\x04grpc\x129\n" +
	"\x05kafka\x18\x03 \x01(\v2\x1b.kratos.api.Transport.KafkaB\x06\xbaH\x03\xc8\x01\x01R\x05kafka\x1ai\n" +
	"\x04HTTP\x12\"\n" +
	"\aaddress\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\aaddress\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\x1ai\n" +
	"\x04GRPC\x12\"\n" +
	"\aaddress\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\aaddress\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\x1a\xe7\x04\n" +
	"\x05Kafka\x12*\n" +
	"\abrokers\x18\x01 \x03(\tB\x10\xbaH\r\x92\x01\n" +
	"\b\x01\x18\x01\"\x04r\x02\x10\x01R\abrokers\x12=\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\atimeout\x12K\n" +
	"\tconsumers\x18\x03 \x01(\v2%.kratos.api.Transport.Kafka.ConsumersB\x06\xbaH\x03\xc8\x01\x01R\tconsumers\x1a\xa5\x03\n" +
	"\tConsumers\x12Y\n" +
	"\vasset_image\x18\x01 \x01(\v20.kratos.api.Transport.Kafka.Consumers.AssetImageB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"assetImage\x1a\xbc\x02\n" +
	"\n" +
	"AssetImage\x12\x1d\n" +
	"\x05topic\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05topic\x12\"\n" +
	"\bgroup_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\x12W\n" +
	"\x06events\x18\x03 \x01(\v27.kratos.api.Transport.Kafka.Consumers.AssetImage.EventsB\x06\xbaH\x03\xc8\x01\x01R\x06events\x1a\x91\x01\n" +
	"\x06Events\x12!\n" +
	"\acreated\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acreated\x12A\n" +
	"\x18object_existence_updated\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x16objectExistenceUpdated\x12!\n" +
	"\adeleted\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\adeleted\"\xd8\x05\n" +
	"\x04Data\x124\n" +
	"\x05mysql\x18\x01 \x01(\v2\x16.kratos.api.Data.MySQLB\x06\xbaH\x03\xc8\x01\x01R\x05mysql\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\xf1\x03\n" +
	"\x05MySQL\x12\x19\n" +
	"\x03dsn\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03dsn\x125\n" +
	"\x14max_open_connections\x18\x02 \x01(\rH\x00R\x12maxOpenConnections\x88\x01\x01\x125\n" +
	"\x14max_idle_connections\x18\x03 \x01(\rH\x01R\x12maxIdleConnections\x88\x01\x01\x12[\n" +
	"\x17max_connection_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x022\x00R\x15maxConnectionLifetime:\xcf\x01\xbaH\xcb\x01\x1a\xc8\x01\n" +
	"\x11mysql.pool_limits\x12Xmax_idle_connections cannot exceed max_open_connections unless max_open_connections is 0\x1aYthis.max_open_connections == 0u || this.max_idle_connections <= this.max_open_connectionsB\x17\n" +
	"\x15_max_open_connectionsB\x17\n" +
	"\x15_max_idle_connections\x1ax\n" +
	"\x05Redis\x12\x19\n" +
	"\x03dsn\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03dsn\x129\n" +
	"\x16max_active_connections\x18\x02 \x01(\rH\x00R\x14maxActiveConnections\x88\x01\x01B\x19\n" +
	"\x17_max_active_connections\"\xe6\x05\n" +
	"\bSecurity\x12K\n" +
	"\faccess_token\x18\x01 \x01(\v2 .kratos.api.Security.AccessTokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12N\n" +
	"\rrefresh_token\x18\x02 \x01(\v2!.kratos.api.Security.RefreshTokenB\x06\xbaH\x03\xc8\x01\x01R\frefreshToken\x12a\n" +
	"\x14email_change_request\x18\x03 \x01(\v2'.kratos.api.Security.EmailChangeRequestB\x06\xbaH\x03\xc8\x01\x01R\x12emailChangeRequest\x12d\n" +
	"\x15avatar_change_request\x18\x04 \x01(\v2(.kratos.api.Security.AvatarChangeRequestB\x06\xbaH\x03\xc8\x01\x01R\x13avatarChangeRequest\x1ah\n" +
	"\vAccessToken\x12\x1f\n" +
	"\x06secret\x18\x01 \x01(\tB\a\xbaH\x04r\x02  R\x06secret\x128\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x03ttl\x1aH\n" +
	"\fRefreshToken\x128\n" +
	"\x03ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x03ttl\x1ao\n" +
	"\x12EmailChangeRequest\x12\x1f\n" +
	"\x06secret\x18\x01 \x01(\tB\a\xbaH\x04r\x02  R\x06secret\x128\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x03ttl\x1aO\n" +
	"\x13AvatarChangeRequest\x128\n" +
	"\x03ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x03ttl\"\x87\x06\n" +
	"\rObservability\x12;\n" +
	"\atracing\x18\x01 \x01(\v2!.kratos.api.Observability.TracingR\atracing\x12;\n" +
	"\ametrics\x18\x02 \x01(\v2!.kratos.api.Observability.MetricsR\ametrics\x1a\x92\x02\n" +
	"\aTracing\x12J\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\".kratos.api.Observability.ProtocolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bprotocol\x12#\n" +
	"\bendpoint\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x122\n" +
	"\rauthorization\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\rauthorization\x88\x01\x01\x12?\n" +
	"\fsample_ratio\x18\x04 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\vsampleRatio\x88\x01\x01B\x10\n" +
	"\x0e_authorizationB\x0f\n" +
	"\r_sample_ratio\x1a\x91\x02\n" +
	"\aMetrics\x12J\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\".kratos.api.Observability.ProtocolB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bprotocol\x12#\n" +
	"\bendpoint\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x122\n" +
	"\rauthorization\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\rauthorization\x88\x01\x01\x12O\n" +
	"\x0fexport_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\x0eexportIntervalB\x10\n" +
	"\x0e_authorization\"S\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPROTOCOL_GRPC\x10\x01\x12\x1a\n" +
	"\x16PROTOCOL_HTTP_PROTOBUF\x10\x02\"\xb2\x01\n" +
	"\aGateway\x127\n" +
	"\x05asset\x18\x01 \x01(\v2\x19.kratos.api.Gateway.AssetB\x06\xbaH\x03\xc8\x01\x01R\x05asset\x1an\n" +
	"\x05Asset\x12#\n" +
	"\bendpoint\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bendpoint\x12@\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\v\xbaH\b\xc8\x01\x01\xaa\x01\x02*\x00R\atimeoutB-Z+github.com/velonyapp/identity/internal/confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_conf_conf_proto_goTypes = []any{
	(Observability_Protocol)(0),                         // 0: kratos.api.Observability.Protocol
	(*Bootstrap)(nil),                                   // 1: kratos.api.Bootstrap
	(*Transport)(nil),                                   // 2: kratos.api.Transport
	(*Data)(nil),                                        // 3: kratos.api.Data
	(*Security)(nil),                                    // 4: kratos.api.Security
	(*Observability)(nil),                               // 5: kratos.api.Observability
	(*Gateway)(nil),                                     // 6: kratos.api.Gateway
	(*Transport_HTTP)(nil),                              // 7: kratos.api.Transport.HTTP
	(*Transport_GRPC)(nil),                              // 8: kratos.api.Transport.GRPC
	(*Transport_Kafka)(nil),                             // 9: kratos.api.Transport.Kafka
	(*Transport_Kafka_Consumers)(nil),                   // 10: kratos.api.Transport.Kafka.Consumers
	(*Transport_Kafka_Consumers_AssetImage)(nil),        // 11: kratos.api.Transport.Kafka.Consumers.AssetImage
	(*Transport_Kafka_Consumers_AssetImage_Events)(nil), // 12: kratos.api.Transport.Kafka.Consumers.AssetImage.Events
	(*Data_MySQL)(nil),                                  // 13: kratos.api.Data.MySQL
	(*Data_Redis)(nil),                                  // 14: kratos.api.Data.Redis
	(*Security_AccessToken)(nil),                        // 15: kratos.api.Security.AccessToken
	(*Security_RefreshToken)(nil),                       // 16: kratos.api.Security.RefreshToken
	(*Security_EmailChangeRequest)(nil),                 // 17: kratos.api.Security.EmailChangeRequest
	(*Security_AvatarChangeRequest)(nil),                // 18: kratos.api.Security.AvatarChangeRequest
	(*Observability_Tracing)(nil),                       // 19: kratos.api.Observability.Tracing
	(*Observability_Metrics)(nil),                       // 20: kratos.api.Observability.Metrics
	(*Gateway_Asset)(nil),                               // 21: kratos.api.Gateway.Asset
	(*durationpb.Duration)(nil),                         // 22: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	2,  // 0: kratos.api.Bootstrap.transport:type_name -> kratos.api.Transport
	3,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	4,  // 2: kratos.api.Bootstrap.security:type_name -> kratos.api.Security
	5,  // 3: kratos.api.Bootstrap.observability:type_name -> kratos.api.Observability
	6,  // 4: kratos.api.Bootstrap.gateway:type_name -> kratos.api.Gateway
	7,  // 5: kratos.api.Transport.http:type_name -> kratos.api.Transport.HTTP
	8,  // 6: kratos.api.Transport.grpc:type_name -> kratos.api.Transport.GRPC
	9,  // 7: kratos.api.Transport.kafka:type_name -> kratos.api.Transport.Kafka
	13, // 8: kratos.api.Data.mysql:type_name -> kratos.api.Data.MySQL
	14, // 9: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	15, // 10: kratos.api.Security.access_token:type_name -> kratos.api.Security.AccessToken
	16, // 11: kratos.api.Security.refresh_token:type_name -> kratos.api.Security.RefreshToken
	17, // 12: kratos.api.Security.email_change_request:type_name -> kratos.api.Security.EmailChangeRequest
	18, // 13: kratos.api.Security.avatar_change_request:type_name -> kratos.api.Security.AvatarChangeRequest
	19, // 14: kratos.api.Observability.tracing:type_name -> kratos.api.Observability.Tracing
	20, // 15: kratos.api.Observability.metrics:type_name -> kratos.api.Observability.Metrics
	21, // 16: kratos.api.Gateway.asset:type_name -> kratos.api.Gateway.Asset
	22, // 17: kratos.api.Transport.HTTP.timeout:type_name -> google.protobuf.Duration
	22, // 18: kratos.api.Transport.GRPC.timeout:type_name -> google.protobuf.Duration
	22, // 19: kratos.api.Transport.Kafka.timeout:type_name -> google.protobuf.Duration
	10, // 20: kratos.api.Transport.Kafka.consumers:type_name -> kratos.api.Transport.Kafka.Consumers
	11, // 21: kratos.api.Transport.Kafka.Consumers.asset_image:type_name -> kratos.api.Transport.Kafka.Consumers.AssetImage
	12, // 22: kratos.api.Transport.Kafka.Consumers.AssetImage.events:type_name -> kratos.api.Transport.Kafka.Consumers.AssetImage.Events
	22, // 23: kratos.api.Data.MySQL.max_connection_lifetime:type_name -> google.protobuf.Duration
	22, // 24: kratos.api.Security.AccessToken.ttl:type_name -> google.protobuf.Duration
	22, // 25: kratos.api.Security.RefreshToken.ttl:type_name -> google.protobuf.Duration
	22, // 26: kratos.api.Security.EmailChangeRequest.ttl:type_name -> google.protobuf.Duration
	22, // 27: kratos.api.Security.AvatarChangeRequest.ttl:type_name -> google.protobuf.Duration
	0,  // 28: kratos.api.Observability.Tracing.protocol:type_name -> kratos.api.Observability.Protocol
	0,  // 29: kratos.api.Observability.Metrics.protocol:type_name -> kratos.api.Observability.Protocol
	22, // 30: kratos.api.Observability.Metrics.export_interval:type_name -> google.protobuf.Duration
	22, // 31: kratos.api.Gateway.Asset.timeout:type_name -> google.protobuf.Duration
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	file_conf_conf_proto_msgTypes[12].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[13].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[18].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		EnumInfos:         file_conf_conf_proto_enumTypes,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
