// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/velony-app/identity/internal/application/command"
	"github.com/velony-app/identity/internal/application/domainevent"
	"github.com/velony-app/identity/internal/application/query"
	"github.com/velony-app/identity/internal/conf"
	"github.com/velony-app/identity/internal/domain/service"
	"github.com/velony-app/identity/internal/infrastructure/auth"
	"github.com/velony-app/identity/internal/infrastructure/data/mysql"
	"github.com/velony-app/identity/internal/infrastructure/data/redis"
	"github.com/velony-app/identity/internal/infrastructure/observability"
	"github.com/velony-app/identity/internal/infrastructure/transport"
	"github.com/velony-app/identity/internal/presentation/api"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(data *conf.Data, confTransport *conf.Transport, confObservability *conf.Observability, confAuth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	db, err := mysql.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	outboxPublisher := mysql.NewOutboxPublisher(db)
	userCreatedHandler := domainevent.NewUserCreatedHandler(outboxPublisher)
	userUsernameChangedHandler := domainevent.NewUserUsernameChangedHandler(outboxPublisher)
	userFullNameChangedHandler := domainevent.NewUserFullNameChangedHandler(outboxPublisher)
	userAvatarKeyChangedHandler := domainevent.NewUserAvatarKeyChangedHandler(outboxPublisher)
	userDeletedHandler := domainevent.NewUserDeletedHandler(outboxPublisher)
	dispatcher := domainevent.NewDispatcher(userCreatedHandler, userUsernameChangedHandler, userFullNameChangedHandler, userAvatarKeyChangedHandler, userDeletedHandler)
	user := mysql.NewUserRepo(db, dispatcher)
	client, err := redis.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	getUserHandler := query.NewGetUserHandler(user, cache)
	batchGetUsersHandler := query.NewBatchGetUsersHandler(user, cache)
	session := mysql.NewSessionRepo(db)
	unitOfWork := mysql.NewUnitOfWork(db)
	tokenProvider := auth.NewTokenProvider(confAuth)
	passwordHasher := auth.NewPasswordHasher()
	usernameAvailability := service.NewUsernameAvailability(user)
	registerAuthHandler := command.NewRegisterAuthHandler(user, session, unitOfWork, tokenProvider, passwordHasher, cache, usernameAvailability)
	loginAuthHandler := command.NewLoginAuthHandler(user, session, unitOfWork, tokenProvider, passwordHasher, cache)
	refreshAuthHandler := command.NewRefreshAuthHandler(user, session, unitOfWork, tokenProvider, cache)
	updateUserHandler := command.NewUpdateUserHandler(user, unitOfWork, cache, usernameAvailability)
	deleteUserHandler := command.NewDeleteUserHandler(user, unitOfWork, cache)
	apiService := api.NewService(getUserHandler, batchGetUsersHandler, registerAuthHandler, loginAuthHandler, refreshAuthHandler, updateUserHandler, deleteUserHandler)
	tracesMiddleware := transport.NewTracesMiddleware()
	metrics, err := observability.NewMetrics()
	if err != nil {
		return nil, nil, err
	}
	metricsMiddleware := transport.NewMetricsMiddleware(metrics)
	authMiddleware := transport.NewAuthMiddleware(confAuth)
	validationMiddleware := transport.NewValidationMiddleware()
	server := transport.NewGRPCServer(confTransport, apiService, tracesMiddleware, metricsMiddleware, authMiddleware, validationMiddleware)
	httpServer := transport.NewHTTPServer(confTransport, apiService, tracesMiddleware, metricsMiddleware, authMiddleware, validationMiddleware)
	app := newApp(logger, server, httpServer)
	return app, func() {
	}, nil
}
