// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v3"
	"github.com/velonyapp/identity/internal/application/command"
	"github.com/velonyapp/identity/internal/application/domainevent"
	"github.com/velonyapp/identity/internal/application/query"
	"github.com/velonyapp/identity/internal/conf"
	"github.com/velonyapp/identity/internal/domain/service"
	"github.com/velonyapp/identity/internal/info"
	"github.com/velonyapp/identity/internal/infrastructure/data/mysql"
	"github.com/velonyapp/identity/internal/infrastructure/data/redis"
	"github.com/velonyapp/identity/internal/infrastructure/event"
	"github.com/velonyapp/identity/internal/infrastructure/gateway"
	observability2 "github.com/velonyapp/identity/internal/infrastructure/observability"
	"github.com/velonyapp/identity/internal/infrastructure/security"
	"github.com/velonyapp/identity/internal/presentation/api"
	"github.com/velonyapp/identity/internal/presentation/observability"
	"github.com/velonyapp/identity/internal/presentation/transport"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, infoService *info.Service, data *conf.Data, confTransport *conf.Transport, confSecurity *conf.Security, confObservability *conf.Observability, confGateway *conf.Gateway, logger *slog.Logger) (*kratos.App, func(), error) {
	db, err := mysql.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	user := mysql.NewUserQuery(db)
	client, err := redis.NewConnection(data)
	if err != nil {
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	getUserHandler := query.NewGetUserHandler(user, cache)
	batchGetUsersHandler := query.NewBatchGetUsersHandler(user, cache)
	encoder := event.NewEncoder()
	eventPublisher := mysql.NewEventPublisher(db, encoder)
	userCreatedHandler := domainevent.NewUserCreatedHandler(eventPublisher)
	userUsernameChangedHandler := domainevent.NewUserUsernameChangedHandler(eventPublisher)
	userEmailChangeRequestedHandler := domainevent.NewUserEmailChangeRequestedHandler(eventPublisher)
	userEmailChangedHandler := domainevent.NewUserEmailChangedHandler(eventPublisher)
	userFullNameChangedHandler := domainevent.NewUserFullNameChangedHandler(eventPublisher)
	userAvatarChangedHandler := domainevent.NewUserAvatarChangedHandler(eventPublisher)
	userDeletedHandler := domainevent.NewUserDeletedHandler(eventPublisher)
	sessionCreatedHandler := domainevent.NewSessionCreatedHandler(eventPublisher)
	sessionRefreshedHandler := domainevent.NewSessionRefreshedHandler(eventPublisher)
	sessionRevokedHandler := domainevent.NewSessionRevokedHandler(eventPublisher)
	dispatcher := domainevent.NewDispatcher(userCreatedHandler, userUsernameChangedHandler, userEmailChangeRequestedHandler, userEmailChangedHandler, userFullNameChangedHandler, userAvatarChangedHandler, userDeletedHandler, sessionCreatedHandler, sessionRefreshedHandler, sessionRevokedHandler)
	repoUser := mysql.NewUserRepo(db, dispatcher)
	session := mysql.NewSessionRepo(db, dispatcher)
	unitOfWork := mysql.NewUnitOfWork(db)
	accessTokenManager := security.NewAccessTokenManager(confSecurity)
	sessionTokenManager := security.NewSessionTokenManager()
	passwordManager := security.NewPasswordManager()
	usernameAvailability := service.NewUsernameAvailability(repoUser)
	registerAuthHandler := command.NewRegisterAuthHandler(confSecurity, repoUser, session, unitOfWork, accessTokenManager, sessionTokenManager, passwordManager, usernameAvailability)
	loginAuthHandler := command.NewLoginAuthHandler(confSecurity, repoUser, session, unitOfWork, accessTokenManager, sessionTokenManager, passwordManager)
	refreshAuthHandler := command.NewRefreshAuthHandler(confSecurity, repoUser, session, unitOfWork, accessTokenManager, sessionTokenManager)
	updateUserHandler := command.NewUpdateUserHandler(repoUser, unitOfWork, cache, usernameAvailability)
	emailAvailability := service.NewEmailAvailability(repoUser)
	requestUserEmailChangeHandler := command.NewRequestUserEmailChangeHandler(confSecurity, repoUser, unitOfWork, emailAvailability)
	requestVerifier := security.NewRequestVerifier(confSecurity)
	confirmUserEmailChangeHandler := command.NewConfirmUserEmailChangeHandler(repoUser, unitOfWork, cache, requestVerifier, emailAvailability)
	assetServiceClient, cleanup, err := gateway.NewAssetClient(confGateway)
	if err != nil {
		return nil, nil, err
	}
	assetService := gateway.NewAssetService(assetServiceClient)
	requestUserAvatarChangeHandler := command.NewRequestUserAvatarChangeHandler(assetService)
	deleteUserHandler := command.NewDeleteUserHandler(repoUser, unitOfWork, cache)
	apiService := api.NewService(getUserHandler, batchGetUsersHandler, registerAuthHandler, loginAuthHandler, refreshAuthHandler, updateUserHandler, requestUserEmailChangeHandler, confirmUserEmailChangeHandler, requestUserAvatarChangeHandler, deleteUserHandler)
	serverMetrics, err := observability.NewServerMetrics()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server := transport.NewGRPCServer(confTransport, apiService, serverMetrics)
	httpServer := transport.NewHTTPServer(confTransport, apiService, serverMetrics)
	kafkaConsumer := transport.NewKafkaConsumer(confTransport, apiService)
	openTelemetry, cleanup2, err := observability2.NewOpenTelemetry(contextContext, confObservability, infoService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, server, httpServer, kafkaConsumer, openTelemetry)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
