name: Publish Image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*"

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1

    permissions:
      contents: read
      packages: write
      id-token: write

    with:
      output: image
      push: true

      platforms: linux/amd64,linux/arm64

      meta-images: ghcr.io/${{ github.repository }}

      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
        type=ref,event=tag
        type=sha

    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
